---
- name: Install java and net-tool
  hosts: webserver
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack Nexus installer
  hosts: webserver
  tasks:
    - name: check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: stat_result
      #- debug: msg={{stat_result.stat.exists}}
    - name: download Nexus
        get_url:
          url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
          dest: /opt/
        register: download_result
    - name: Untar nexus installer
      unarchive:
        src: "{{download_result.dest}}" ## this is the name of the tar file that got downloaded
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists     
    - name: Find nexus folder
      find:
        path: /opt/
        patter: "nexus-*"
        file_type: directory
      register: find_result
    #- debug: msg={{find_result}} # inf you want to see the result printed
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Creat a new user to own nexus folder
  hosts: webserver
  tasks:
    - name: Ensure group nexus exist
      group:
        name: nexus
        state: present
    - name: Creat nexus user
      user: 
      name: nexus
      group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: webserver
  become: True
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      blockinfile:
        path: /opt/nexus/bin/nexus.rc
        block:
          run_as_user="nexus"
      ## this module below lets you change and existing line with another
      #lineinfile:
        #path: /opt/nexus/bin/nexus.rc
        #regexp: '^#run_as_uuser=""'
        #line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start
# the fact that you execute a playbook and its successfull, it doesnt mean your application is runing. always check, there could be a server storage problem. 
      
- name: Verify nexus running
  hosts: nexus server
  tasks:
    - name: check with ps
      shell: ps aux | grep nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      pause:
        minutes: 1 
    - name: Check with netstat
      shell: netstat plnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


