- name: Copy docker compose
  copy:
    src: docker-compose.yaml # ansible sensible enough to locate the file its self
    dest: /home/ayaba/docker-compose.yaml

- name: Docker login
  docker_login:
    registry_url: "{{ docker_registry }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}" #providing password as an external variable file or interactive prompt

- name: Start container from compose
  docker_compose:
    project_src: /home/ayaba